In [2]:
import numpy as np

## 1. Vectors

In [3]:
# Creating vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a =", a)
print("b =", b)
print("shape:", a.shape)

a = [1 2 3]
b = [4 5 6]
shape: (3,)


In [4]:
# Vector operations
print("Addition:            ", a + b)
print("Subtraction:         ", a - b)
print("Scalar multiply (3a):", 3 * a)

Addition:             [5 7 9]
Subtraction:          [-3 -3 -3]
Scalar multiply (3a): [3 6 9]


In [5]:
# Dot product
dot = np.dot(a, b)
print("Dot product a·b:", dot)

# Same using @
print("Using @:        ", a @ b)

Dot product a·b: 32
Using @:         32


In [6]:
# Norm (magnitude)
norm_a = np.linalg.norm(a)
print("||a|| =", norm_a)

# Angle between a and b
cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle = np.degrees(np.arccos(cos_theta))
print(f"Angle between a and b: {angle:.2f}°")

||a|| = 3.7416573867739413
Angle between a and b: 12.93°


In [7]:
# Cross product (3D only)
cross = np.cross(a, b)
print("Cross product a×b:", cross)
print("Dot with a (should be 0):", np.dot(cross, a))  # perpendicular check
print("Dot with b (should be 0):", np.dot(cross, b))

Cross product a×b: [-3  6 -3]
Dot with a (should be 0): 0
Dot with b (should be 0): 0


## 2. Matrices

In [8]:
# Creating matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A =\n", A)
print("shape:", A.shape)

A =
 [[1 2]
 [3 4]]
shape: (2, 2)


In [9]:
# Special matrices
print("Identity (3x3):\n", np.eye(3))
print("\nZeros (2x3):\n", np.zeros((2, 3)))
print("\nDiagonal:\n", np.diag([3, 7, 4]))

Identity (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

Diagonal:
 [[3 0 0]
 [0 7 0]
 [0 0 4]]


In [10]:
# Matrix operations
print("A + B:\n", A + B)
print("\nA - B:\n", A - B)
print("\n3 * A:\n", 3 * A)
print("\nElement-wise A * B:\n", A * B)
print("\nMatrix multiply A @ B:\n", A @ B)

A + B:
 [[ 6  8]
 [10 12]]

A - B:
 [[-4 -4]
 [-4 -4]]

3 * A:
 [[ 3  6]
 [ 9 12]]

Element-wise A * B:
 [[ 5 12]
 [21 32]]

Matrix multiply A @ B:
 [[19 22]
 [43 50]]


                                                                                                                                                        
```
● Element-wise multiplication (*) is used when you want to scale each element independently — not combine rows and columns.

Common uses:

1. Applying a mask / weights
data   = np.array([[10, 20], [30, 40]])
mask   = np.array([[1, 0], [0, 1]])   # keep diagonal only

data * mask  →  [[10, 0], [0, 40]]

2. Neural networks — applying activation element-wise
weights = np.array([0.5, 0.2, 0.8])
inputs  = np.array([1.0, 2.0, 3.0])

weights * inputs   # scale each input by its weight independently
→ [0.5, 0.4, 2.4]  

3. Image processing
image  = np.array([[255, 200], [100, 50]])
filter = np.array([[0.5, 0.5], [0.5, 0.5]])  # darken

image * filter  →  [[127.5, 100], [50, 25]]

---
Rule of thumb:

┌─────────────────────────────┬──────────────────────────────────┐
│     Use @ (matrix mul)      │       Use * (element-wise)       │
├─────────────────────────────┼──────────────────────────────────┤
│ Transforming vectors/space  │ Scaling individual values        │
├─────────────────────────────┼──────────────────────────────────┤
│ Linear algebra operations   │ Applying weights, masks, filters │
├─────────────────────────────┼──────────────────────────────────┤
│ Combining row × column info │ Each element is independent      │
└─────────────────────────────┴──────────────────────────────────┘
```

In [11]:
# Transpose
print("A =\n", A)
print("\nA transpose:\n", A.T)

A =
 [[1 2]
 [3 4]]

A transpose:
 [[1 3]
 [2 4]]


In [ ]:
# Determinant
print("det(A) =", np.linalg.det(A))

singular = np.array([[1, 2], 
                     [2, 4]])
print("det(singular) =", np.linalg.det(singular))   # should be 0

det(A) = -2.0000000000000004
det(singular) = 0.0


In [13]:
# Inverse
A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)
print("\nA @ A_inv (should be I):\n", np.round(A @ A_inv))

A inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (should be I):
 [[1. 0.]
 [0. 1.]]


In [14]:
# Solve system of linear equations: Ax = b
# 2x + y = 8
# 5x + 3y = 21
A_sys = np.array([[2, 1], [5, 3]])
b_sys = np.array([8, 21])

x = np.linalg.solve(A_sys, b_sys)
print("Solution x =", x)
print("Verify A @ x =", A_sys @ x)   # should equal b

Solution x = [3. 2.]
Verify A @ x = [ 8. 21.]


# Vectors & Matrices — NumPy Coding

In [6]:
import numpy as np
std_basis = np.array([[1, 0],[0,1]])
non_std_basis = np.array([[2, 0],[0,3]])
inv_non_std_basis = np.linalg.inv(non_std_basis)
vector_in_std_basis = np.array([4,6])
that_vector_in_non_std_basis = inv_non_std_basis @ vector_in_std_basis
print(that_vector_in_non_std_basis)
print("Verify ", non_std_basis @ that_vector_in_non_std_basis )

[2. 2.]
Verify  [4. 6.]


In [18]:
import numpy as np

def find_eigenvalues(matrix):
    vals = np.linalg.eigvals(matrix)
    ev, _ = np.linalg.eig(matrix)
    # return [round(v.real, 2) for v in vals]
    # return [round(v.real, 2) for v in vals]
    # return [round(v.real, 2) for v in ev]
    # return list(ev)
    return sorted(ev.tolist())

matrix = [[4, 1], [2, 3]]
print(find_eigenvalues(matrix))   # [5.0, 2.0]

[2.0, 5.0]
